spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/cuartelbomberos
    username: root
    password: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true